python -m train \
-d mnist \
-e 15 \
-b 128 \
-l cross_entropy \
-o rmsprop \
-lr 0.001 \
-wd 0 \
-nhl 2 \
-sz 128 64 \
-a tanh \
-w_i random \
--model_save_path best_model.npy \
--run_name "Hyperparameter Tuning: relu2" \
--wandb_project hyperparameter_tuning \